# This workflow will do a clean install of node dependencies, build the source code and run tests with node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push]

jobs:
  variant_reassingment_build:
    name: Node variant reassignment build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: serializing workflow runs
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          same-branch-only: false
      - name: Use Node.js 8.9
        uses: actions/setup-node@v2
        with:
          node-version: '8.9'
      - run: npm i
      - run: npm install -g codecov
      - run: npm run test
      - run: codecov
        env:
          SPHERE_PROJECT_KEY: node-variant-reassignment-tests
          SPHERE_CLIENT_ID: ${{ secrets.SPHERE_CLIENT_ID }}
          SPHERE_CLIENT_SECRET: ${{ secrets.SPHERE_CLIENT_SECRET }}
